# Softmax Classification

- softmax
- cross entropy
- low-level implementation
- high-level implementation
- training example

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

torch.manual_seed(1)

## Discrete Probability Distribution (이산확률분포)

- 이산확률분포란, 확률분포함수가 이어지지 않는 방식으로 나온다
- 즉 a, c, e라는 x가 존재할 때 a와 c 사이의 b에 대한 확률이 존재하지 않게 된다. 
- 이런 이산확률분포에서 특정 값에 대한 예측을 진행하는 것이 softmax 함수이다. 

In [2]:
z = torch.FloatTensor([1, 2, 3])

hypothesis = F.softmax(z, dim=0)
print(hypothesis)

tensor([0.0900, 0.2447, 0.6652])


In [3]:
hypothesis.sum()

tensor(1.)

## Cross Entropy

- 두 분포 사이의 차이를 측정하는데 활용한다. 
- classification에서 모델이 예측한 확률 분포와 실제 확률 분포의 차이를 확인할 때 사용한다. 
- CE(p, q) = - Σ y * log(Y) (y = 실제 정답, Y = 모델이 예측한 확률) = - Σ p(x) log( q(x) )
- 정답에 가까울 수록 loss가 작아진다

In [4]:
z = torch.rand(3, 5, requires_grad=True)
hypothesis = F.softmax(z, dim=1)
print(hypothesis)

tensor([[0.2645, 0.1639, 0.1855, 0.2585, 0.1277],
        [0.2430, 0.1624, 0.2322, 0.1930, 0.1694],
        [0.2226, 0.1986, 0.2326, 0.1594, 0.1868]], grad_fn=<SoftmaxBackward0>)


In [6]:
y = torch.randint(5, (3, )).long()
print(y)

tensor([0, 2, 1])
