In [1]:
import numpy as np
import torch

## 1D Array with Numpy
- 1차원 배열을 numpy를 통해 초기화한다. 

In [ ]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])
print(t)
print('Rank of t : ', t.ndim)
print('Shape of t : ', t.shape)

[0. 1. 2. 3. 4. 5. 6.]
Rank of t :  1
Shape of t :  (7,)


## 2D Array with Numpy
- 2차원 배열(행렬)을 numpy를 통해 초기화한다.
- Rank는 차원, Shape은 x, y축의 크기를 알려준다. 

In [4]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
print(t)
print('Rank of t : ', t.ndim)
print('Shape of t : ', t.shape)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]
Rank of t :  2
Shape of t :  (4, 3)


## 1D Array with PyTorch
- dim : 차원
- shape : 차원당 원소 개수
- size : 차원당 원소 개수(=shape)

In [ ]:
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t)

print(t.dim())
print(t.shape)
print(t.size())
print(t[0], t[1], t[-1])
print(t[2:5], t[4:-1])
print(t[:2], t[3:])

tensor([0., 1., 2., 3., 4., 5., 6.])


## 2D Array with Pytorch

In [8]:
t = torch.FloatTensor([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])

print(t)

print(t.dim())
print(t.shape)
print(t.size())

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])
2
torch.Size([4, 3])
torch.Size([4, 3])


## BroadCasting
- 행렬 의 덧셈, 뺄셈에선 두 Tensor간의 크기가 같아야 한다. 
- 행렬곱을 수행할 때, 마지막 차원과 첫 차원이 일치해야 한다. 
- 하지만 불가피하게 다른 크기 행렬간의 사칙연산이 필요해진다. 
- PyTorch의 BroadCasting은 자동적으로 차원을 맞춰준다. 

In [9]:
a1 = torch.FloatTensor([[3, 3]])
a2 = torch.FloatTensor([[2, 2]])

print(a1 + a2)

b1 = torch.FloatTensor([[1, 2]])
b2 = torch.FloatTensor([3])

print(b1 + b2)

c1 = torch.FloatTensor([[1, 2]])
c2 = torch.FloatTensor([[3], [4]])

print(c1 + c2)

tensor([[5., 5.]])
tensor([[4., 5.]])
tensor([[4., 5.],
        [5., 6.]])


## Multiplication vs Matrix Multiplication
- 자동적인 동작이 되기 때문에 휴먼 에러를 조심해야 한다. 
- 에러 없이 BroadCasting이 되기 때문에 디버깅이 어렵다. 
- 사칙연산의 `*`를 사용하면 행렬곱이 아닌, 요소 곱으로 나온다. 
- 행렬곱을 사용할 때 `@`를 사용하면 된다. 

In [11]:
print('----------\nMul vs Matmul\n----------')
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('shape of m1 : ', m1.shape)
print('shape of m2 : ', m2.shape)
print(m1 @ m2)
print(m1.matmul(m2))
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print(m1 * m2)
print(m1.mul(m2))

----------
Mul vs Matmul
----------
shape of m1 :  torch.Size([2, 2])
shape of m2 :  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])
tensor([[ 5.],
        [11.]])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


## Mean(평균)
- Long타입의 경우 평균을 구하지 못하는 경우가 존재한다. 
- `dim`파라미터를 통해 특정 차원에 대한 평균값을 구할 수 있다. 
- `Sum`에 대해서도 같은 방식으로 동작하게 된다. 

In [17]:
try:
    t = torch.LongTensor([1, 2])
    print(t.mean())
except Exception as exc:
    print(exc)

t = torch.FloatTensor([[1, 2], [3, 4]])
print(t.mean())
print(t.mean(dim=0))
print(t.mean(dim=1))
print(t.mean(dim=-1))

mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long
tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


## Max and ArgMax
- max는 행렬에서 최대값을 찾아준다. 
- 뒤에 dim을 붙일 수 있다. 
- dim=0일 때 [2, 1]크기로 만들어준다.(세로로 최대값 비교를 해 가장 큰값을 모은 행렬로 만들어준다. )
- dim=1일 때 [1, 2]크기로 만들어준다. 
- 이 때 max에 인덱스를 붙여 확인이 가능하다. dim에 대해 max를 구하면, 0인덱스는 최대값행렬을, 1인덱스는 최대값행렬에 들어간 원소의 각 행/렬 상의 인덱스를 반환한다. 

In [20]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)
print(t.max())
print(t.max(dim=0)[0])
print(t.max(dim=0)[1])
print(t.max(dim=1)[0])
print(t.max(dim=1)[1])

tensor([[1., 2.],
        [3., 4.]])
tensor(4.)
tensor([3., 4.])
tensor([1, 1])
tensor([2., 4.])
tensor([1, 1])


## View
- `view`는 `reshape`와 동일한 동작을 수행한다. 
- 총 원소 개수는 유지하면서 파라미터로 지정한 형태에 따라 재구성한다. 
- `view`의 파라미터로 배열이 들어가며, 입력된 값의 크기를 고정값으로 행렬을 재구성한다. 
- 이 때 `-1`이 입력되면 해당 값은 다른 크기에 따라 유동적으로 크기를 설정한다. 

In [25]:
t = np.array([[[0, 1, 2], [3, 4, 5]], [[6, 7, 8], [9, 10, 11]]])
ft = torch.FloatTensor(t)

print(ft.shape)

print(ft.view([-1, 3]))
print(ft.view([-1, 3]).shape)

print(ft.view([-1, 1, 3]))
print(ft.view([-1, 1, 3]).shape)

torch.Size([2, 2, 3])
tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])
tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


## Squeeze
- 크기가 1인 차원을 모두 제거한다. 
- 구조를 단순화시킬 때 이용한다. 

In [26]:
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape)

print(ft.squeeze())
print(ft.squeeze().shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])
tensor([0., 1., 2.])
torch.Size([3])


## Unsqueeze

- 차원 확장에 이용한다.
- 특정 차원에 크기가 1인 차원을 추가해준다. 
- 그러면 unsqueeze하고 나서 squeeze하면 다시 원복될까?


In [ ]:
ft = torch.FloatTensor([0, 1, 2])
print(ft.shape)

print(ft.unsqueeze(0))
print(ft.unsqueeze(0).shape)
print(ft.unsqueeze(1).shape)

x = torch.tensor([[1, 2, 3], [4, 5, 6]])  # shape: (2,3)
print(x.shape)

x_unsqueezed = torch.unsqueeze(x, 0)  # 첫 번째 차원에 추가
print(x_unsqueezed.shape)  # torch.Size([1, 2, 3])

x_unsqueezed = torch.unsqueeze(x, 1)  # 두 번째 차원에 추가
print(x_unsqueezed.shape)  # torch.Size([2, 1, 3])

x_unsqueezed = torch.unsqueeze(x, 2)  # 세 번째 차원에 추가
print(x_unsqueezed.shape)  # torch.Size([2, 3, 1])

torch.Size([3])
tensor([[0., 1., 2.]])
torch.Size([1, 3])
torch.Size([3, 1])
torch.Size([2, 3])
torch.Size([1, 2, 3])
torch.Size([2, 1, 3])
torch.Size([2, 3, 1])
torch.Size([2, 3])


## Type Casting
- 타입별 함수를 통해 텐서의 타입을 변환해줄 수 있다. 

In [18]:
lt = torch.LongTensor([1, 2, 3, 4])

print(lt.float())
bt = torch.ByteTensor([True, False, False, True])
print(bt.long())
print(bt.float())

tensor([1., 2., 3., 4.])
tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


## Concatenate
- 텐서를 연결할 수 있다. 
- dim을 파라미터로 받아 확장시킨다 ex. (2, 2), (2, 2)인 텐서를 cat할 때 dim = 0이라면 (4, 2)가. dim=1이라면 (2,4)가 된다. 
- 텐서에 존재하지 않는 차원을 파라미터로 주면 에러
- dim으로 연결되는 행렬 값의 수가 같아야 한다
    - (2, 2), (3, 2)의 벡터를 dim=0에 대해 concatenate한다면 (5, 2)가 되지만 dim=1에 대해 concatinate할 수 없다. 

In [ ]:
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])

print(torch.cat([x, y], dim=0))
print(torch.cat([x, y], dim=1))

torch.Size([3, 2])
tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])


RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 2 but got size 3 for tensor number 1 in the list.

## Stacking
- 여러 텐서를 새로운 차원에 쌓는다. 
- cat은 행렬값을 합친 결과로 같은 차원의 크기가 다른 벡터를 반환하지만, stack은 차원이 변경된다. 

In [29]:
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

print(torch.stack([x, y, z]))
print(torch.stack([x, y, z]).shape)
print(torch.stack([x, y, z], dim=1))
print(torch.stack([x, y, z], dim=1).shape)

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
torch.Size([3, 2])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.Size([2, 3])


## Ones and Zeros
- 기존 텐서와 같은 크기와 데이터타입을 가지며 모든 값이 0(zeros_like), 1(ones_like)인 텐서를 반환한다 

In [30]:
x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])

print(torch.ones_like(x))
print(torch.zeros_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


## In-place Operation
- 텐서에 대한 원소곱을 수행한다. 
- `mul`로 수행할 경우 원소곱을 반환하지만 실제 텐서에는 영향을 주지 않는다. 
- `mul_`로 수행할 경우 실제 텐서에 원소곱을 해준 후 해당 텐서를 반환한다. 

In [31]:
x = torch.FloatTensor([[[1, 2], [3, 4]]])

print(x.mul(2.0))
print(x)
print(x.mul_(2.0))
print(x)

tensor([[[2., 4.],
         [6., 8.]]])
tensor([[[1., 2.],
         [3., 4.]]])
tensor([[[2., 4.],
         [6., 8.]]])
tensor([[[2., 4.],
         [6., 8.]]])
