In [1]:
import numpy as np
import torch

## 1D Array with Numpy
- 1차원 배열을 numpy를 통해 초기화한다. 

In [ ]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])
print(t)
print('Rank of t : ', t.ndim)
print('Shape of t : ', t.shape)

[0. 1. 2. 3. 4. 5. 6.]
Rank of t :  1
Shape of t :  (7,)


## 2D Array with Numpy
- 2차원 배열(행렬)을 numpy를 통해 초기화한다.
- Rank는 차원, Shape은 x, y축의 크기를 알려준다. 

In [4]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
print(t)
print('Rank of t : ', t.ndim)
print('Shape of t : ', t.shape)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]
Rank of t :  2
Shape of t :  (4, 3)


## 1D Array with PyTorch
- dim : 차원
- shape : 차원당 원소 개수
- size : 차원당 원소 개수(=shape)

In [ ]:
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t)

print(t.dim())
print(t.shape)
print(t.size())
print(t[0], t[1], t[-1])
print(t[2:5], t[4:-1])
print(t[:2], t[3:])

tensor([0., 1., 2., 3., 4., 5., 6.])


## 2D Array with Pytorch

In [8]:
t = torch.FloatTensor([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])

print(t)

print(t.dim())
print(t.shape)
print(t.size())

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])
2
torch.Size([4, 3])
torch.Size([4, 3])


## BroadCasting
- 행렬 의 덧셈, 뺄셈에선 두 Tensor간의 크기가 같아야 한다. 
- 행렬곱을 수행할 때, 마지막 차원과 첫 차원이 일치해야 한다. 
- 하지만 불가피하게 다른 크기 행렬간의 사칙연산이 필요해진다. 
- PyTorch의 BroadCasting은 자동적으로 차원을 맞춰준다. 

In [9]:
a1 = torch.FloatTensor([[3, 3]])
a2 = torch.FloatTensor([[2, 2]])

print(a1 + a2)

b1 = torch.FloatTensor([[1, 2]])
b2 = torch.FloatTensor([3])

print(b1 + b2)

c1 = torch.FloatTensor([[1, 2]])
c2 = torch.FloatTensor([[3], [4]])

print(c1 + c2)

tensor([[5., 5.]])
tensor([[4., 5.]])
tensor([[4., 5.],
        [5., 6.]])


## Multiplication vs Matrix Multiplication
- 자동적인 동작이 되기 때문에 휴먼 에러를 조심해야 한다. 
- 에러 없이 BroadCasting이 되기 때문에 디버깅이 어렵다. 
- 사칙연산의 `*`를 사용하면 행렬곱이 아닌, 요소 곱으로 나온다. 
- 행렬곱을 사용할 때 `@`를 사용하면 된다. 

In [11]:
print('----------\nMul vs Matmul\n----------')
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('shape of m1 : ', m1.shape)
print('shape of m2 : ', m2.shape)
print(m1 @ m2)
print(m1.matmul(m2))
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print(m1 * m2)
print(m1.mul(m2))

----------
Mul vs Matmul
----------
shape of m1 :  torch.Size([2, 2])
shape of m2 :  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])
tensor([[ 5.],
        [11.]])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


## Mean(평균)
- Long타입의 경우 평균을 구하지 못하는 경우가 존재한다. 
- `dim`파라미터를 통해 특정 차원에 대한 평균값을 구할 수 있다. 
- `Sum`에 대해서도 같은 방식으로 동작하게 된다. 

In [17]:
try:
    t = torch.LongTensor([1, 2])
    print(t.mean())
except Exception as exc:
    print(exc)

t = torch.FloatTensor([[1, 2], [3, 4]])
print(t.mean())
print(t.mean(dim=0))
print(t.mean(dim=1))
print(t.mean(dim=-1))

mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long
tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


## Max and ArgMax
- max는 행렬에서 최대값을 찾아준다. 
- 뒤에 dim을 붙일 수 있다. 
- dim=0일 때 [2, 1]크기로 만들어준다.(세로로 최대값 비교를 해 가장 큰값을 모은 행렬로 만들어준다. )
- dim=1일 때 [1, 2]크기로 만들어준다. 
- 이 때 max에 인덱스를 붙여 확인이 가능하다. dim에 대해 max를 구하면, 0인덱스는 최대값행렬을, 1인덱스는 최대값행렬에 들어간 원소의 각 행/렬 상의 인덱스를 반환한다. 

In [20]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)
print(t.max())
print(t.max(dim=0)[0])
print(t.max(dim=0)[1])
print(t.max(dim=1)[0])
print(t.max(dim=1)[1])

tensor([[1., 2.],
        [3., 4.]])
tensor(4.)
tensor([3., 4.])
tensor([1, 1])
tensor([2., 4.])
tensor([1, 1])


## View
- `view`는 `reshape`와 동일한 동작을 수행한다. 
- 총 원소 개수는 유지하면서 파라미터로 지정한 형태에 따라 재구성한다. 
- `view`의 파라미터로 배열이 들어가며, 입력된 값의 크기를 고정값으로 행렬을 재구성한다. 
- 이 때 `-1`이 입력되면 해당 값은 다른 크기에 따라 유동적으로 크기를 설정한다. 

In [25]:
t = np.array([[[0, 1, 2], [3, 4, 5]], [[6, 7, 8], [9, 10, 11]]])
ft = torch.FloatTensor(t)

print(ft.shape)

print(ft.view([-1, 3]))
print(ft.view([-1, 3]).shape)

print(ft.view([-1, 1, 3]))
print(ft.view([-1, 1, 3]).shape)

torch.Size([2, 2, 3])
tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])
tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


## Squeeze
- 크기가 1인 차원을 모두 제거한다. 
- 구조를 단순화시킬 때 이용한다. 

In [26]:
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape)

print(ft.squeeze())
print(ft.squeeze().shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])
tensor([0., 1., 2.])
torch.Size([3])


## Unsqueeze


In [27]:
ft = torch.FloatTensor([0, 1, 2])
print(ft.shape)

print(ft.unsqueeze(0))
print(ft.unsqueeze(0).shape)

torch.Size([3])
tensor([[0., 1., 2.]])
torch.Size([1, 3])
